### PR TITLE
feat(wip): plot maud posterior distributions

### PR DESCRIPTION
**Pull request by carrascomj**
Related to #1 

### Description

Given a `StanVariable`, a `MaudInput` and the output of the simulation in the form of `InferenceData`, plot the posterior distribution of that variable in the form of a violin, with priors as point ranges (95% confidence).

### Implementation details

* Returns a `plotnine` plot, so the user can continue configuring.
* It only works for things that can be a `StanVariable` and that are in the `PriorSets`; that is, no balanced concentrations, fluxes, etc.

* [x] Missing tests.
* [ ] Missing non `StanVariable`s.

### Examples

Given some data:

```python
import arviz as az
from plotnine import *
from maud.loading_maud_inputs import load_maud_input
from maud.data_model.stan_variable_set import Dgf, ConcUnbalanced

mi = load_maud_input("../data")
infd = az.from_netcdf(SAMPLES_DIR / ".." / "idata.nc")
```

Plot dGf.

```python
(
    plot_maud_posterior(infd, mi.priors, Dgf)
    + coord_flip()
    + geom_hline(yintercept=0, color="#CCCCCC", linetype="--")
    + theme_tufte()
)
```

Or unbalance concentrations.

```python
(
    plot_maud_posterior(infd, mi.priors, ConcUnbalanced)
    + scale_y_continuous(trans="log10")
    + theme(legend_position="none")
)
```

### CODE REVIEW

**Comment by teddygroves** [comment]
This looks great!

The same approach should also work for concentrations and fluxes, but this will require changes in Maud (specifically adding corresponding `StanVariable`s, and probably also introducing a distinction between `StanVariable`s that are parameters and have priors and others). In the meantime I suggest we just tidy this up and use it more or less as is. 

One change that might be nice would be to separate the logic for plotting posteriors from logic for plotting priors, as only the former can later be reused for variables that don't have priors like balanced concentrations.

**Comment by carrascomj** [comment]
I have separated the prior and posterior plot logic. Now, the user can

```python
# standalone prior
plot_maud_prior(infd, mi.priors, Dgf, concat=False)
# or both plots, overlayed
plot_maud_posterior(infd, Dgf) + plot_maud_prior(infd, mi.priors, Dgf)
# or the same as the latter but shorter
plot_maud_variable(infd, mi.priors, Dgf)
```

I had to use a hack to concatenate the plots conditionally, which is a shortcoming of the ggplot implementation of grammar graphics. Altair does it better, but its violin plots are a bit underwhelming.

**Comment by carrascomj** [comment]
Okay! I cannot write tests for now since we need some maud output to test it, they should be added at some point.

**Comment by teddygroves** [comment]
This pr comes with a methionine output: #15, should hopefully work.

**Comment by carrascomj** [comment]
I added some tests now. It might be better to squash and merge because I rebased it from master.

**Pull request merged**
